"""empty message

Revision ID: ab1de0c23e80
Revises: 39c3d5e25cd4
Create Date: 2016-10-13 13:48:21.661382

"""

# revision identifiers, used by Alembic.
revision = 'ab1de0c23e80'
down_revision = '39c3d5e25cd4'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Business')
    op.drop_table('Invoices')
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Invoices',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('invoiceNumber', sa.VARCHAR(length=120), nullable=True),
    sa.Column('clientName', sa.VARCHAR(length=120), nullable=True),
    sa.Column('clientEmail', sa.VARCHAR(length=120), nullable=True),
    sa.Column('businessId', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoiceAmt', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoiceDueDate', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoiceDate', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoiceDesc', sa.VARCHAR(length=30), nullable=True),
    sa.Column('invoiceOpened', sa.BOOLEAN(), nullable=True),
    sa.Column('invoicePaid', sa.BOOLEAN(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Business',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('authenticated', sa.BOOLEAN(), nullable=True),
    sa.Column('name', sa.VARCHAR(length=120), nullable=True),
    sa.Column('company', sa.VARCHAR(length=120), nullable=True),
    sa.Column('email', sa.VARCHAR(length=120), nullable=True),
    sa.Column('password', sa.VARCHAR(length=30), nullable=True),
    sa.Column('phone', sa.VARCHAR(length=120), nullable=True),
    sa.Column('website', sa.VARCHAR(length=120), nullable=True),
    sa.Column('street', sa.VARCHAR(length=120), nullable=True),
    sa.Column('city', sa.VARCHAR(length=120), nullable=True),
    sa.Column('state', sa.VARCHAR(length=120), nullable=True),
    sa.Column('country', sa.VARCHAR(length=120), nullable=True),
    sa.Column('zipCode', sa.VARCHAR(length=120), nullable=True),
    sa.Column('vatTaxNo', sa.VARCHAR(length=120), nullable=True),
    sa.Column('logo', sa.VARCHAR(length=120), nullable=True),
    sa.Column('stripeToken', sa.VARCHAR(length=120), nullable=True),
    sa.Column('stripeUserId', sa.VARCHAR(length=120), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    ### end Alembic commands ###
